name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - master
jobs:
    autotest:
        runs-on: ubuntu-latest
        steps:
            with:
                node-version: 14
          - name: auto test
                run: |
                    npm i
                    npm run test
